const ERROR_TYPES = {
	ER_DECRYPTION: 'ER_DECRYPTION',
	ER_ENCRYPTION: 'ER_ENCRYPTION',
	ER_GEN_UNKNOWN: 'ER_GEN_UNKNOWN',
	ER_IDEN_OBJECT: 'ER_IDEN_OBJECT',
	ER_MAL_RESPONSE: 'ER_MAL_RESPONSE',
	ER_NOT_FOUND: 'ER_NOT_FOUND',
	ER_UNIQ_CONSTRAINT: 'ER_UNIQ_CONSTRAINT'
};

module.exports = {
	ERROR_TYPES
};
